### ISSUE TITLE
能不能增加一个搜索栏

### ISSUE THREAD

**Issue by waimao8** [x1ah/gena-template#2]
这个导航站非常方便，添加网站也很简单，就只缺一个搜索栏就完美了

**Comment by x1ah** [comment]
@waimao8 支持搜索框的，把下面这个添加到你的配置文件里就可以

```yaml
webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu
```
